
{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
package:
    name: wsdt

    version: {{ setup_py_data.version }}
  
source:
  path: ../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python >=3.7
    - numpy >=1.12
    - vigra >=1.11
    - networkx

test:
  source_files:
    - tests
  
  requires:
    # numpy allocation tracking not rebuilt for newer versions
    - python 3.7
    - nose
    - numpy-allocation-tracking # This package can be found in the ilastik channel

  imports:
    - wsdt

  commands:
    - nosetests tests
  
about:
  summary: Implementation of a distance-transform-based watershed algorithm
